version: 2
jobs:
  build:
    docker:
      - image: cimg/node:lts
    branches:
      only: circleci-project-setup
    steps:
      - checkout
      - run:
          name: Install
          command: yarn install
      - save_cache:
          paths:
            - node_modules
          key: dependencies-
      - run:
          name: Gatsby build site
          command: yarn build